"""
Course data and global constants.
"""

ALL_DAY_CUTOFF  = (23, 59)   # 시간 제한 없이 하루 전체 슬롯 수집

TEE_INTERVAL_MINUTES = {
    "River Oaks Golf Course":         10,
    "Lorette Golf Course":            8,
    "Quarry Oaks Golf Course":        10,
    "Rossmere Country Club":          8,
    "St. Boniface Golf Club":         10,
    "Bridges Golf Course":            10,
    "Larters at St. Andrews Golf Course": 10,
    "John Blumberg Golf Course":      10,
    "Southside Golf Course":          10,
    "Windsor Park Golf Course":       10,
    "_default":                       10,
}

OPEN_KEYWORDS = [
    "open for play", "still open", "now open", "course is open",
    "book a tee time", "book tee time", "tee time", "reserve a tee",
    "fall hours", "fall rates", "closing soon", "last round",
    "season extended", "late season",
]
CLOSED_KEYWORDS = [
    "closed for the season", "see you next", "season has ended",
    "closed until", "off season", "시즌 종료",
]

# Courses with dedicated scrapers
# system must match a scraper in scrapers/<system>.py
INDIVIDUAL_COURSES = [
    {
        "name": "River Oaks Golf Course",
        "booking_url": "https://www.tee-on.com/PubGolf/servlet/com.teeon.teesheet.servlets.golfersection.ComboLanding?CourseCode=RIOA&FromCourseWebsite=true",
        "homepage": "https://www.riveroaksgolf.ca/",
        "phone": "(204) 261-4653",
        "system": "tee_on",
        "distance_km": 25,
        "holes": 18,
        "fallback_price": 77,
        "cart_mandatory": False,
    },
    {
        "name": "Lorette Golf Course",
        "booking_url": "https://www.tee-on.com/PubGolf/servlet/com.teeon.teesheet.servlets.golfersection.ComboLanding?CourseCode=LORE&FromCourseWebsite=true",
        "homepage": "https://www.lorettegolf.com/",
        "phone": "(204) 878-2172",
        "system": "tee_on",
        "distance_km": 22,
        "holes": 18,
        "fallback_price": 73,
        "cart_mandatory": False,
        "early_bird_price": 41,
    },
    {
        "name": "Quarry Oaks Golf Course",
        "booking_url": "https://secure.east.prophetservices.com/LinksatQuarryOaksV3",
        "homepage": "https://www.quarryoaks.com/",
        "phone": "(204) 326-4653",
        "system": "prophetservices",
        "distance_km": 48,
        "holes": 27,
        "fallback_price": 74,
        "cart_mandatory": False,
    },
    {
        "name": "Rossmere Country Club",
        "booking_url": "https://rossmeregc.clubhouseonline-e3.net/PublicTeeTimes/TeeSheet.aspx",
        "homepage": "https://www.rossmeregcc.com/",
        "phone": "(204) 988-1540",
        "system": "clubhouse_online",
        "distance_km": 18,
        "holes": 18,
        "fallback_price": 62,
        "cart_mandatory": False,
    },
    {
        "name": "St. Boniface Golf Club",
        "booking_url": "https://stbonifacegolfclub.clubhouseonline-e3.net/PublicTeeTimes/TeeSheet",
        "homepage": "https://www.stbonifacegolfclub.com/",
        "phone": "(204) 233-4276",
        "system": "clubhouse_online",
        "distance_km": 10,
        "holes": 18,
        "fallback_price": 85,
        "cart_mandatory": False,
    },
    {
        "name": "Bridges Golf Course",
        "booking_url": "https://bridgesgccan.cps.golf/onlineresweb/search-teetime?TeeOffTimeMin=0&TeeOffTimeMax=23.999722222222225",
        "homepage": "https://www.bridgesgolfcourse.com/",
        "phone": "(204) 735-3000",
        "system": "cps_golf",
        "distance_km": 45,
        "holes": 18,
        "fallback_price": 85,
        "cart_mandatory": True,
    },
    {
        "name": "Larters at St. Andrews Golf Course",
        "booking_url": "https://www.tee-on.com/PubGolf/servlet/com.teeon.teesheet.servlets.golfersection.ComboLanding?CourseCode=LART&FromCourseWebsite=true",
        "homepage": "https://www.larters.com/",
        "phone": "(204) 334-2107",
        "system": "tee_on",
        "distance_km": 22,
        "holes": 18,
        "fallback_price": 57,
        "cart_mandatory": False,
    },
    {
        "name": "Kingswood Golf & Country Club",
        "booking_url": "https://kingswood-golf-country-club.book.teeitup.com/",
        "homepage": "https://www.kingswoodgolf.ca/",
        "phone": "(204) 736-4079",
        "system": "teeitup",
        "distance_km": 29,
        "holes": 18,
        "fallback_price": 40,
        "cart_mandatory": False,
    },
    {
        "name": "Maplewood Golf Club",
        "booking_url": "https://maplewood-golf-club.book.teeitup.com/",
        "homepage": "https://maplewood.golf/",
        "phone": "(204) 433-3344",
        "system": "teeitup",
        "distance_km": 58,
        "holes": 18,
        "fallback_price": 51,
        "cart_mandatory": False,
    },
    {
        "name": "John Blumberg Golf Course",
        "booking_url": "https://john-blumberg-golf-course.book.teeitup.com/",
        "homepage": "https://www.johnblumberggolf.com/",
        "phone": "(204) 986-3490",
        "system": "teeitup",
        "distance_km": 17,
        "holes": 27,
        "fallback_price": 50,
        "cart_mandatory": False,
    },
    {
        "name": "Assiniboine Golf Club",
        "booking_url": "https://assiniboine-golf-club.book.teeitup.com/",
        "homepage": "https://www.assiniboinegolfclub.com/",
        "phone": None,
        "system": "teeitup",
        "distance_km": 15,
        "holes": 9,
        "fallback_price": None,
        "cart_mandatory": False,
    },
    {
        "name": "Bel Acres Golf and Country Club",
        "booking_url": "https://belacres.cps.golf/",
        "homepage": "https://www.belacres.com/",
        "phone": "(204) 632-8337",
        "system": "cps_golf_belacres",
        "distance_km": 24,
        "holes": 18,
        "fallback_price": 65,
        "cart_mandatory": False,
    },
    {
        "name": "Whispering Winds of Warren",
        "booking_url": "https://whispering-winds-of-warren-golf-and-country-club.book.teeitup.com/",
        "homepage": "https://www.whisperingwindsofwarren.com/",
        "phone": "(204) 322-5104",
        "system": "teeitup",
        "distance_km": 62,
        "holes": 18,
        "fallback_price": 68,
        "cart_mandatory": False,
    },
    {
        "name": "Southside Golf Course",
        "booking_url": "https://www.tee-on.com/PubGolf/servlet/com.teeon.teesheet.servlets.golfersection.ComboLanding?CourseCode=STHS&FromCourseWebsite=true",
        "homepage": "https://www.southsidegolf.ca/",
        "phone": "(204) 254-6709",
        "system": "tee_on",
        "distance_km": 25,
        "holes": 18,
        "fallback_price": 38,
        "cart_mandatory": False,
        "tuesday_2for1": True,
    },
    {
        "name": "Oakwood Golf Course",
        "booking_url": "https://admin.teeon.com/portal/oakwoodgc/teetimes/oakwoodgc",
        "homepage": "https://www.oakwoodgolf.net/",
        "phone": "(204) 422-8045",
        "system": "teeon_portal",
        "distance_km": 20,
        "holes": 18,
        "fallback_price": 26,
        "cart_mandatory": False,
    },
    {
        "name": "Windsor Park Golf Course",
        "booking_url": "https://www.tee-on.com/PubGolf/servlet/com.teeon.teesheet.servlets.golfersection.WebBookingSearchSteps?FromTrailSearch=true&OriginalReferrer=https://www.winnipeg.ca/&FromCourseWebsite=true&CourseCode=WIPA&CourseGroupID=11354&Referrer=www.tee-on.com",
        "homepage": "https://www.winnipeg.ca/recreation-leisure/golf-courses/windsor-park",
        "phone": "(204) 986-3006",
        "system": "tee_on",
        "distance_km": 10,
        "holes": 18,
        "fallback_price": 48,
        "cart_mandatory": False,
    },
]

# Courses fetched via GolfNow API (duplicates vs INDIVIDUAL_COURSES are auto-skipped)
GOLFNOW_COURSES = {
    "assiniboine": {
        "facility_id": "15887",
        "name": "Assiniboine Golf Club",
        "slug": "assiniboine-golf-club",
        "distance_km": 15,
        "holes": 9,
        "homepage": "https://www.assiniboinegolfclub.com/",
        "phone": None,
        "fallback_price": None,
    },
    "bel_acres": {
        "facility_id": "15442",
        "name": "Bel Acres Golf and Country Club",
        "slug": "bel-acres-golf-and-country-club",
        "distance_km": 24,
        "holes": 18,
        "homepage": "https://www.belacres.com/",
        "phone": "(204) 632-8337",
        "fallback_price": 65,
    },
    "whispering_winds": {
        "facility_id": "16952",
        "name": "Whispering Winds of Warren",
        "slug": "whispering-winds-of-warren-golf-and-country-club",
        "distance_km": 62,
        "holes": 18,
        "homepage": "https://www.whisperingwindsofwarren.com/",
        "phone": "(204) 322-5104",
        "fallback_price": 68,
    },
    "larters": {
        "facility_id": "17167",
        "name": "Larters at St. Andrews Golf Course",
        "slug": "larters-at-st-andrews-golf-country-club",
        "distance_km": 22,
        "holes": 18,
        "homepage": "https://www.larters.com/",
        "phone": "(204) 334-2107",
        "fallback_price": 57,
    },
}
